version: '2.1'

volumes:
  grafana_data: {}
  prometheus_data: {}
  influx_data: {}

services:
  influxdb:
    image: influxdb:1.7.7
    container_name: influxdb
    environment:
      - INFLUXDB_DB=prometheus
      - INFLUXDB_USER=admin
      - INFLUXDB_USER_PASSWORD=admin
    ports:
      - 8086:8086
    volumes:
     - influx_data:/var/lib/influxdb
    network_mode: 'host'

  # nodeexporter:
  #   image: prom/node-exporter:v0.18.1
  #   container_name: nodeexporter
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   command:
  #     - '--path.procfs=/host/proc'
  #     - '--path.rootfs=/rootfs'
  #     - '--path.sysfs=/host/sys'
  #     - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
  #   restart: unless-stopped
  #   expose:
  #     - 9100
  #   labels:
  #     org.label-schema.group: "monitoring"
  #   network_mode: 'host'

  prometheus:
    image: prom/prometheus:v2.11.1
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - influxdb
      # - nodeexporter
    network_mode: 'host'
  
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/plugins/:/var/lib/grafana/plugins
    env_file:
      - ./grafana/config.monitoring
    network_mode: 'host'
  
  # alertmanager:
  #   image: prom/alertmanager
  #   ports:
  #     - 9093:9093
  #   volumes:
  #     - ./alertmanager/:/etc/alertmanager/
  #   restart: always
  #   network_mode: 'host'
  #   command:
  #     - '--config.file=/etc/alertmanager/config.yml'
  #     - '--storage.path=/alertmanager'
